cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'imagemagick'
brew 'jp2a'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'rg'
brew 'roundup'
brew 'wget'
brew 'youtube-dl'
brew 'vim'
brew 'bash-completion'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'hub'
brew 'ctags'
brew 'fzf'
brew 'tldr'

cask '1password'
cask 'adium'
cask 'alfred'
cask 'atom'
cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'evernote'
cask 'filezilla'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'licecap'
cask 'mapbox-studio'
cask 'slack'
cask 'spectacle'
cask 'skype'
cask 'sqlitebrowser'
cask 'transmission'
cask 'tunnelbear'
