#!/bin/bash

### Symlink dotfiles
ln -sf $(pwd)/home/.* $HOME/

### Install Plug and plugins
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim -es -u ~/.vimrc +PlugInstall +qa

### Install ctags
ctags -R --exclude=.git--exclude=vendor --exclude=node_modules --exclude=db --exclude=log .
