#!/bin/bash

### Symlink dotfiles
ln -sf $(pwd)/home/.* $HOME/

### Install Plug and plugins
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim -es -u vimrc -i NONE -c "PlugInstall" -c "qa"

